# GLOBAL SITE SETTINGS
cname: inspire.yourwebvisual.com
allow_robots: false

# META
title: Inspire
title_homepage: Inspire | Enterprise Wide
company: Enterprise Wide
description:

# DEVELOPER
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/inspire-0118
github_repo_name: inspire-0118
jekyll_version: 3.7.0

# OFFICES
offices:
  - title: Manly Office
    address: 55 North Steyne<br> Manly NSW
    phone: (05) 555 555
    email: info@enterprisewide.com.au

# SOCIAL MEDIA
social_media:
  - title: Behance
    url: '#'
    icon: fa fa-behance

  - title: Codepen
    url: '#'
    icon: fa fa-codepen

  - title: Dribbble
    url: '#'
    icon: fa fa-dribbble

  - title: Facebook
    url: '#'
    icon: fa fa-facebook

  - title: Flickr
    url: '#'
    icon: fa fa-flickr

  - title: Github
    url: '#'
    icon: fa fa-github

  - title: Google Plus
    url: '#'
    icon: fa fa-google-plus

  - title: Instagram
    url: '#'
    icon: fa fa-instagram

  - title: LinkedIn
    url: '#'
    icon: fa fa-linkedin

  - title: Pinterest
    url: '#'
    icon: fa fa-pinterest

  - title: RSS
    url: '#'
    icon: fa fa-rss

  - title: SnapChat
    url: '#'
    icon: fa fa-snapchat

  - title: SoundCloud
    url: '#'
    icon: fa fa-soundcloud

  - title: Slack
    url: '#'
    icon: fa fa-slack

  - title: Tumblr
    url: '#'
    icon: fa fa-tumblr

  - title: Twitter
    url: '#'
    icon: fa fa-twitter

  - title: Youtube
    url: '#'
    icon: fa fa-youtube-play

  - title: Vimeo
    url: '#'
    icon: fa fa-vimeo

# GOOGLE
google_analytics: 'UA-XXXXXXXX-X'

# AUTHOR
author:
  title: Ben Norman
  url: http://enterprisewide.com.au
  logo: /assets/img/ui/ewide-logo.svg
  description: Powered by Enterprise Wide