# GLOBAL SITE SETTINGS
cname: inspire.yourwebvisual.com
allow_robots: false

# META
title: Inspire
title_homepage: Inspire | Enterprise Wide
company: Enterprise Wide
description:

# DEVELOPER
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/inspire-0118
github_repo_name: inspire-0118
jekyll_version: 3.7.0

# OFFICES
offices:
  - title: Manly Office
    address: 55 North Steyne<br> Manly NSW
    phone: (05) 555 555
    email: info@enterprisewide.com.au

# SOCIAL MEDIA
social_media:
  - title: Facebook
    url: '#'
  - title: Twitter
    url: '#'
  - title: LinkedIn
    url: '#'
  - title: Google+
    url: '#'
  - title: Pinterest
    url: '#'
  - title: Instagram
    url: '#'
  - title: Flickr
    url: '#'
  - title: Tumblr
    url: '#'
  - title: Vimeo
    url: '#'
  - title: YouTube
    url: '#'
  - title: Behance
    url: '#'
  - title: Soundcloud
    url: '#'
  - title: RSS
    url: '#'

# GOOGLE
google_analytics: 'UA-XXXXXXXX-X'

# AUTHOR
author:
  title: Ben Norman
  url: http://enterprisewide.com.au
  logo: /assets/img/ui/ewide-logo.svg
  description: Powered by Enterprise Wide